/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_etb_lab_svg2png_Svg2Png */

#ifndef _Included_com_etb_lab_svg2png_Svg2Png
#define _Included_com_etb_lab_svg2png_Svg2Png
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_etb_lab_svg2png_Svg2Png
 * Method:    renderSVG
 * Signature: (Ljava/lang/String;Ljava/lang/String;DII)I
 */
JNIEXPORT jint JNICALL Java_com_etb_1lab_svg2png_Svg2Png_renderSVG
  (JNIEnv *, jclass, jstring, jstring, jdouble, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
